[project]
name = "inferancia-chat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.118.0",
    "langchain>=0.3.27",
    "langchain-cerebras>=0.5.0",
    "langgraph>=0.6.8",
]
